name: CI

on:
  push:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.18.1'
      - run: go test ./...